# Generated by Django 5.1.5 on 2025-03-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaccount',
            name='email',
            field=models.EmailField(default='default@gmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationsession',
            name='email',
            field=models.EmailField(default='default@gmail.com', max_length=100),
        ),
    ]
