# Generated by Django 5.1.5 on 2025-03-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_businessaccount_email_registrationsession_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaccount',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='registrationsession',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
