# Generated by Django 5.1.5 on 2025-03-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_businessaccount_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaccount',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='registrationsession',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
