# Generated by Django 5.1.5 on 2025-03-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_businessaccount_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationsession',
            name='logo',
            field=models.ImageField(upload_to='temp/business/images/'),
        ),
    ]
