# Generated by Django 5.1.5 on 2025-03-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_alter_registrationsession_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationsession',
            name='logo',
            field=models.ImageField(upload_to='business/images/'),
        ),
    ]
