# Generated by Django 5.1.5 on 2025-03-18 21:36

import business.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_businessaccount_facebook_businessaccount_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/photos/')),
                ('job_description', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('business', models.ForeignKey(default=business.models.get_default_business, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='business.businessaccount')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(default=business.models.get_default_business, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='business.businessaccount')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='business.portfolioitem')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.tag')),
            ],
            options={
                'unique_together': {('portfolio_item', 'tag')},
            },
        ),
    ]
