# Generated by Django 5.1.5 on 2025-03-19 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_tag_employee_portfolioitem_portfoliotag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
