# Generated by Django 5.2 on 2025-04-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_schedule_staffappointment_availability_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffappointment',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='staffappointment',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='staffappointment',
            name='client_phone',
        ),
        migrations.RemoveField(
            model_name='staffappointment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='staffappointment',
            name='service',
        ),
        migrations.RemoveField(
            model_name='staffappointment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='staffappointment',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staffappointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programada'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('pending', 'Pendiente')], default='scheduled', max_length=20),
        ),
    ]
