# Generated by Django 5.1.6 on 2025-04-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
