# Generated by Django 5.2 on 2025-04-21 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_remove_staffappointment_client_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffAppointment',
        ),
    ]
