# Generated by Django 5.2 on 2025-04-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_delete_staffappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='customer_satisfaction',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
