# Generated by Django 5.1.5 on 2025-04-23 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_remove_staffappointment_client_email_and_more'),
        ('business', '0014_alter_appointment_duration_minutes'),
    ]

    operations = [
    ]
