# Generated by Django 5.1.7 on 2025-04-24 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_merge_20250423_1411'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer_satisfaction',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='no_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='repeat_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='StaffAppointment',
        ),
    ]
