# Generated by Django 5.2 on 2025-04-22 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_alter_appointment_customer_satisfaction'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
