# Generated by Django 5.2 on 2025-04-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_appointment_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='repeat_customer',
            field=models.BooleanField(default=False),
        ),
    ]
