# Generated by Django 5.2 on 2025-04-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_alter_appointment_repeat_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='no_show',
            field=models.BooleanField(default=False),
        ),
    ]
