# Generated by Django 5.2 on 2025-04-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_alter_appointment_no_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
