# Generated by Django 5.2 on 2025-04-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_alter_appointment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
