# Generated by Django 5.1.6 on 2025-04-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_business',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
    ]
